name: "registration"
description: |
  Subworkflow to perform registration between a moving and a fixed image (e.g. T1 -> DWI).
  It requires as input at least a moving (ch_image) and a reference (ch_ref) image to properly
  perform registration.

  Output transformations curated for images for use with the REGISTRATION_ANTSAPPLYTRANSFORMS module
  are available under the names `forward_image_transform` and `backward_image_transform`. The same lists
  are also available for tractograms (`forward_tractogram_transform` and `backward_tractogram_transform`).
  However, to use the REGISTRATION_TRACTOGRAM module, you have to use the `backward_affine` and `backward_warp`
  channels provided by this subworkflow.

  Registration suites:
  - EasyReg (ML): params.run_easyreg = true

    module: REGISTRATION_EASYREG

    Run freesurfer EasyReg any-to-any modality registration.

    NOTE: Outputs a combined warp field only, no affine transformations are available. CANNOT BE LINKED WITH THE BUNDLE_SEG SUBWORKFLOW.

  - Synthmorph (ML): params.run_synthmorph = true

    module: REGISTRATION_SYNTHMORPH

    Run SynthMorph any-to-any modality registration. By default, the algorithm is configured to
    run a chain of affin+deformable transformations, making it suitable for use with most modules
    and subworkflows like BUNDLE_SEG.

    NOTE: the output affine transformation file is in .lta format and needs to be converted to .mat to be used with ANTs using the REGISTRATION_CONVERT module.

  - ANTs (SyN+SyN Quick): params.run_easyreg = false && params.run_synthmorph = false

    module: REGISTRATION_ANTS or REGISTRATION_ANATTODWI

    Run ANTs registration using antsRegistrationSyN.sh (quick version also available).

    NOTE : Transformation to DWI space is available. To trigger it, supply a metric file (ch_metric) in DWI space (e.g. FA map) in addition to the moving (ch_image) and reference (ch_ref) images.
keywords:
  - Registration
  - Transformation
  - DWI
  - Anatomical
components:
  - registration/anattodwi
  - registration/ants
  - registration/convert
  - registration/easyreg
  - registration/synthmorph
  - utils_options
input:
  - ch_fixed_image:
      type: file
      description: |
        The input channel containing the fixed image files. If performing
        registration to DWI space, this is the reference image (e.g. b0 image).
      structure:
        - meta:
            type: map
            description: Metadata map.
        - fixed_image:
            type: file
            description: Fixed image file.
      pattern: "*.{nii,nii.gz}"
      mandatory: true
  - ch_moving_image:
      type: file
      description: |
        Input channel containing the moving image files. If performing
        registration to DWI space, this is the anatomical image to be registered.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - image:
            type: file
            description: Moving image file.
      pattern: "*.{nii,nii.gz}"
      mandatory: true
  - ch_metric:
      type: file
      description: |
        FOR USE WITH REGISTRATION TO DWI SPACE ONLY. The input channel containing the metric files, typically a FA map.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - metric:
            type: file
            description: Metric image file (e.g., FA map).
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_fixed_mask:
      type: file
      description: |
        FOR USE WITH ANTS SYN REGISTRATION ONLY. The input channel containing the mask file in fixed image space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - mask:
            type: file
            description: Fixed image mask file.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_segmentation:
      type: file
      description: |
        FOR USE WITH SYNTHMORPH REGISTRATION ONLY. The input channel containing the SynthSeg v2 (non-robust)
        segmentation + parcellation in fixed image space (reference in Easyreg naming convention) image.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_moving_segmentation:
      type: file
      description: |
        FOR USE WITH SYNTHMORPH REGISTRATION ONLY. The input channel containing the SynthSeg v2 (non-robust)
        segmentation + parcellation in moving image space (floating in Easyreg naming convention) image.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - options:
      type: map
      description: Map of options for the registration subworkflow.
      mandatory: false
      entries:
        run_easyreg:
          type: boolean
          description: Run EasyReg for registration. If false, SynthMorph will be used if `run_synthmorph` is true, and ANTs SyN will be used if `run_synthmorph` is false.
          default: false
        run_synthmorph:
          type: boolean
          description: Run SynthMorph for registration. If false, EasyReg will be used if `run_easyreg` is true, and ANTs SyN will be used if `run_easyreg` is false.
          default: false
output:
  - image_warped:
      type: file
      description: |
        Channel containing images warped in fixed space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - image:
            type: file
            description: Warped image in fixed space.
      pattern: "*.{nii,nii.gz}"
  - reference_warped:
      type: file
      description: |
        ONLY PROVIDED BY REGISTRATION_EASYREG. Channel containing the reference image warped in moving space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - image:
            type: file
            description: Warped reference image in moving space.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - forward_affine:
      type: file
      description: |
        Channel containing the affine transformation matrix to fixed space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - forward_affine:
            type: file
            description: Forward affine transformation file.
      pattern: "*__forward*.{lta,mat}"
      mandatory: false
  - forward_warp:
      type: file
      description: |
        Channel containing the deformation field to fixed space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - forward_warp:
            type: file
            description: Forward warp deformation field.
      pattern: "*__forward*.{nii,nii.gz}"
      mandatory: false
  - backward_warp:
      type: file
      description: |
        Channel containing the deformation field to moving space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - backward_warp:
            type: file
            description: Backward warp deformation field.
      pattern: "*__backward*.{nii,nii.gz}"
      mandatory: false
  - backward_affine:
      type: file
      description: |
        Channel containing the affine transformation matrix to moving space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - backward_affine:
            type: file
            description: Backward affine transformation file.
      pattern: "*__backward*.{lta,mat}"
      mandatory: false
  - forward_image_transform:
      type: list
      description: |
        Channel containing the transformation tuples to warp images to fixed space,
        in the correct order for REGISTRATION_ANTSAPPLYTRANSFORMS.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - transforms:
            type: file
            description: List of forward transformation files.
      pattern: "*__forward*.{nii,nii.gz,mat,lta}"
  - backward_image_transform:
      type: list
      description: |
        Channel containing the transformation tuples to warp images to moving space,
        in the correct order for REGISTRATION_ANTSAPPLYTRANSFORMS.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - transforms:
            type: file
            description: List of backward transformation files.
      pattern: "*__backward*.{nii,nii.gz,mat,lta}"
  - forward_tractogram_transform:
      type: list
      description: |
        Channel containing the transformation tuples to warp tractograms to fixed space,
        in the correct order for REGISTRATION_TRANSFORMTRACTOGRAM.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - transforms:
            type: file
            description: List of transformation files for tractograms.
      pattern: "*__backward*.{nii,nii.gz,mat,lta}"
  - backward_tractogram_transform:
      type: list
      description: |
        Channel containing the transformation tuples to warp tractograms to moving space,
        in the correct order for REGISTRATION_TRANSFORMTRACTOGRAM.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - transforms:
            type: file
            description: List of transformation files for tractograms.
      pattern: "*__forward*.{nii,nii.gz,mat,lta}"
  - segmentation:
      type: file
      description: |
        ONLY PROVIDED BY REGISTRATION_SYNTHMORPH. Channel containing the SynthSeg v2 (non-robust)
        segmentation + parcellation in moving space (floating in Easyreg naming convention).
      structure:
        - meta:
            type: map
            description: Metadata map.
        - segmentation:
            type: file
            description: Segmentation image file.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - reference_segmentation:
      type: file
      description: |
        ONLY PROVIDED BY REGISTRATION_SYNTHMORPH. Channel containing the SynthSeg v2 (non-robust)
        segmentation + parcellation in fixed space (reference in Easyreg naming convention).
      structure:
        - meta:
            type: map
            description: Metadata map.
        - reference_segmentation:
            type: file
            description: Reference segmentation image file.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - mqc:
      type: file
      description: |
        Channel containing the MultiQC report data for the registration.
      structure:
        - mqc:
            type: file
            description: MultiQC report file.
      pattern: "*mqc.*"
      mandatory: false
  - versions:
      type: file
      description: |
        File containing software versions used.
      structure:
        - versions:
            type: file
            description: Versions YAML file.
      pattern: "versions.yml"
authors:
  - "@gagnonanthony"
  - "@AlexVCaron"
