name: "io_bids"
description: |
  Subworkflow loading files from a BIDS directory. It is used in conjunction
  with the IO_READBIDS module which uses the scilpy CLI script to parse the
  BIDS directory and fetch the metadata.

  ------------- Current supported files/metadata -------------

  Files:
    - T1w
    - White matter parcellation from FreeSurfer.
    - Grey matter parcellation from FreeSurfer.
    - Diffusion weighted images (dwi)
    - B-values (bval)
    - B-vectors (bvec)
    - Reverse encoded diffusion weighted images (rev_dwi)
    - B-values for the rev_dwi (rev_bval)
    - B-vectors for the rev_dwi (rev_bvec)
    - Reverse b0 image (rev_b0)

  Metadata (within the meta):
    - Subject ID (id)
    - Session ID (ses)
    - Run ID (run)
    - DWI Total Readout Time (dwi_tr)
    - DWI Phase Encoding Direction (dwi_phase)
    - Reverse DWI Phase Encoding Direction (dwi_revphase)

  **Note**: This subworkflow is meant to be an example of how to use the
  IO_READBIDS module. It only supports a single BIDS folder as an input.
  It can be modified to fit the user's needs.

keywords:
  - IO
  - BIDS
  - Files

components:
  - io/readbids

input:
  - bids_folder:
      type: directory
      description: |
        Path to the BIDS directory. (You must supply only a single BIDS directory)
      structure:
        - bids_folder:
            type: directory
            description: BIDS directory path.
  - fs_folder:
      type: directory
      description: |
        Path to the FreeSurfer directory.
      structure:
        - fs_folder:
            type: directory
            description: FreeSurfer directory path.
      mandatory: false
  - bidsignore:
      type: file
      description: |
        Path to the .bidsignore file.
      structure:
        - bidsignore:
            type: file
            description: BIDS ignore file.
      mandatory: false
output:
  - ch_t1:
      type: file
      description: |
        Channel containing all T1w files
      structure:
        - meta:
            type: map
            description: Metadata map.
        - t1:
            type: file
            description: T1-weighted image file.
      pattern: "*.nii.gz"
  - ch_wmparc:
      type: file
      description: |
        Channel containing all FreeSurfer white matter parcellation files.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - wmparc:
            type: file
            description: FreeSurfer white matter parcellation file.
      pattern: "*.mgz"
      mandatory: false
  - ch_aparc_aseg:
      type: file
      description: |
        Channel containing all FreeSurfer grey matter parcellation files.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - aparc_aseg:
            type: file
            description: FreeSurfer grey matter parcellation file.
      pattern: "*.mgz"
      mandatory: false
  - ch_dwi_bval_bvec:
      type: file
      description: |
        Channel containing all diffusion weighted images, b-values and b-vectors.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - dwi:
            type: file
            description: DWI file.
        - bval:
            type: file
            description: B-values file.
        - bvec:
            type: file
            description: B-vectors file.
      pattern: "*.{nii.gz,bval,bvec}"
  - ch_rev_dwi_bval_bvec:
      type: file
      description: |
        Channel containing all reverse encoded diffusion weighted images, b-values and b-vectors.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - rev_dwi:
            type: file
            description: Reverse-encoded DWI file.
        - rev_bval:
            type: file
            description: B-values file for reverse-encoded DWI.
        - rev_bvec:
            type: file
            description: B-vectors file for reverse-encoded DWI.
      pattern: "*.{nii.gz,bval,bvec}"
      mandatory: false
  - ch_rev_b0:
      type: file
      description: |
        Channel containing all reverse b0 images.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - rev_b0:
            type: file
            description: Reverse b0 image file.
      pattern: "*.nii.gz"
      mandatory: false
  - versions:
      type: file
      description: |
        File containing software versions
      structure:
        - versions:
            type: file
            description: Versions YAML file.
      pattern: "versions.yml"
authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
