# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "atlas_roimetrics"
description: |
  This subworkflow will compute the mean and standard deviation of each provided metric map
  for each bundle mask of the configured atlas. The subworkflow takes as input the reference
  image from each subject (e.g. the B0). The atlas template reference image is registered
  to the subject's DWI space. The transformation is then applied on the bundle masks for each
  subject, allowing us to have the bundle masks in the same space as the input metric images (i.e.
  in the subject's DWI space).
keywords:
  - atlas
  - bundles
  - neuroimaging
  - template
  - iit
  - roi
  - metrics
  - stats
components:
  - atlas_iit
  - registration/ants
  - stats/metricsinroi
  - registration/antsapplytransforms
input:
  - ch_subject_reference:
      type: file
      description: |
        Reference image from each subject on which the
        atlas' reference image will be registered. This
        image is in the subject's DWI space.
        Structure: [ val(meta), path(b0) ]
      pattern: "*.nii.gz"
      ontologies:
        - edam: http://edamontology.org/format_4001 # NIFTI format
  - ch_metrics:
      type: file
      description: |
        List of metric maps for each subject in the subject's DWI space.
        Structure: [ val(meta), [ path(metric1), path(metric2), ... ] ]
      pattern: "*.nii.gz"
      ontologies:
        - edam: http://edamontology.org/format_4001 # NIFTI format
  - options:
      type: map
      description: |
        Map of options for the subworkflow, including:
          - use_atlas_iit (bool): If 'true', the IIT Human Brain Atlas will be used for ROI metrics extraction.
          - use_binary_masks (bool): If 'true', the IIT bundle masks will be thresholded to create binary masks before extracting the metrics.
          - atlas_iit_b0 (str): Path to a Mean B0 map of the IIT Human Brain Atlas. If provided, this input will be used instead of downloading the Mean B0 map.
          - atlas_iit_bundle_masks_dir (str): Path to a directory containing IIT bundle masks. If provided, these inputs will be used instead of downloading and processing the bundle masks.
      mandatory: true
      default:
        - use_atlas_iit: true
        - use_binary_masks: false
        - atlas_iit_b0: null
        - atlas_iit_bundle_masks_dir: null

  - options:
      type: channel
      description: |
        Map of options for the subworkflow, including:
          - threshold_bundles (bool): If enabled, this will threshold the TDI bundle maps with the
            recommended thresholds to create binary bundle masks. If disabled, the subworkflow will
            output the TDI bundle maps.
          - smooth_sigma (float): If `threshold_bundles` is enabled, this will apply a gaussian smoothing
            with the specified sigma to the TDI bundle maps before thresholding. This is based on the
            recommendation of the IIT atlas authors to apply some smoothing to the TDI maps before thresholding.
      mandatory: false
      default:
        - threshold_bundles: false
        - smooth_sigma: 1.0
output:
  - json:
      type: file
      description: |
        List of binary bundle masks.
        Structure: [ path(img), path(img), ... ]
      pattern: "*.nii.gz"
      ontologies:
        - edam: http://edamontology.org/format_4001 # NIFTI format
  - stats_tab_mean:
      type: file
      description: |
        Structured tabular (TSV or CSV) file holding MEAN metrics
        values for each bundle mask. The tabular file has the following
        column structure: (sample, roi, metric1, metric2, ..., metricN).
        Structure: [ val(meta), path(tab_mean) ]
      pattern: "*_desc-mean_*.{csv,tsv}"
      ontologies: []
  - stats_tab_std:
      type: file
      description: |
        Structured tabular (TSV or CSV) file holding STANDARD
        DEVIATION metrics values for each bundle mask. The
        tabular file has the following column structure:
        (sample, roi, metric1, metric2, ..., metricN).
        Structure: [ val(meta), path(tab_std) ]
      pattern: "*_desc-std_*.{csv,tsv}"
      ontologies: []
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@levje"
maintainers:
  - "@levje"
