name: "topup_eddy"
description: |
  Subworkflow performing distorsions correction/eddy correction/motion correction.
  If a reverse B0 or a reverse DWI is provided it will run topup and then eddy,
  otherwise only eddy will run.

  ---------  Steps  --------------------

  1. PREPROC_TOPUP (topup, FSL)
    Prepare data and apply FSL topup
  2. PREPROC_EDDY (eddy, FSL)
    Apply Eddy (and Topup if already run)
  3. UTILS_EXTRACTb0 (scilpy, scilus)
    Extract a b0 volume from a DWI image.
keywords:
  - preprocessing
  - dwi
  - topup
  - eddy
  - distorsion
  - extract_b0
components:
  - preproc/topup
  - preproc/eddy
  - utils/extractb0
  - getoptionswithdefaults
input:
  - ch_dwi:
      type: file
      description: |
        The input channel containing the DWI file, B-values and B-vectors in FSL format files.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - dwi:
            type: file
            description: DWI image file.
        - bval:
            type: file
            description: B-values in FSL format.
        - bvec:
            type: file
            description: B-vectors in FSL format.
      pattern: "*{.nii,.nii.gz,.bval,.bvec}"
  - ch_b0:
      type: file
      description: |
        The input channel containing the b0 reference for the DWI.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - b0:
            type: file
            description: B0 image file.
      pattern: "*{.nii,.nii.gz}"
      mandatory: false
  - ch_rev_dwi:
      type: file
      description: |
        The input channel containing the reverse DWI file, B-values and B-vectors in FSL format files.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - rev_dwi:
            type: file
            description: Reverse phase-encoded DWI image file.
        - bval:
            type: file
            description: B-values in FSL format.
        - bvec:
            type: file
            description: B-vectors in FSL format.
      pattern: "*{.nii,.nii.gz,.bval,.bvec}"
      mandatory: false
  - ch_rev_b0:
      type: file
      description: |
        The input channel containing the reverse b0 file.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - rev_b0:
            type: file
            description: Reverse phase-encoded B0 image file.
      pattern: "*{.nii,.nii.gz}"
      mandatory: false
  - config_topup:
      type: file
      description: |
        Topup config file. Optional. See https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/TopupUsersGuide#Configuration_files
      structure:
        - config_topup:
            type: file
            description: Topup configuration file.
      pattern: "*cnf"
      mandatory: false
  - options:
      type: map
      description: Map of options for the topup_eddy subworkflow.
      mandatory: false
      entries:
        topup_eddy_run_topup:
          type: boolean
          description: Run FSL Topup for distorsion correction.
          default: true
        topup_eddy_run_eddy:
          type: boolean
          description: Run FSL Eddy for motion and eddy current correction.
          default: true
output:
  - dwi:
      type: file
      description: |
        Nifti volume - DWI corrected
      structure:
        - meta:
            type: map
            description: Metadata map.
        - dwi:
            type: file
            description: Corrected DWI image file.
      pattern: "*__dwi_corrected.nii.gz"
  - bval:
      type: file
      description: |
        B-values corrected in FSL format
      structure:
        - meta:
            type: map
            description: Metadata map.
        - bval:
            type: file
            description: Corrected B-values file.
      pattern: "*__bval_eddy"
  - bvec:
      type: file
      description: |
        B-vectors corrected in FSL format
      structure:
        - meta:
            type: map
            description: Metadata map.
        - bvec:
            type: file
            description: Corrected B-vectors file.
      pattern: "*__dwi_eddy_corrected.bvec"
  - b0:
      type: file
      description: |
        Nifti volume - b0 corrected
      structure:
        - meta:
            type: map
            description: Metadata map.
        - b0:
            type: file
            description: Corrected B0 image file.
      pattern: "*__b0_mask.nii.gz"
  - b0_mask:
      type: file
      description: |
        Nifti volume - Mask for b0 corrected
      structure:
        - meta:
            type: map
            description: Metadata map.
        - b0_mask:
            type: file
            description: B0 mask file.
      pattern: "*__b0_bet_mask.nii.gz"
  - mqc:
      type: file
      description: |
        Channel containing the quality control images for MultiQC.
      structure:
        - mqc:
            type: file
            description: Quality control images.
      pattern: "*_mqc.{gif,png}"
      mandatory: false
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@arnaudbore"
