# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-neuro/modules/main/subworkflows/meta-schema.json
name: "load_test_data"

description: |
  Download test datasets for modules and subworkflows. A full listing of the packages ids
  is available in the nf-neuro repository, under `tests/test_data.json`.
keywords:
  - load
  - test
  - data
  - scilpy
components: []
input:
  - ch_archive:
      type: string
      description: |
        Input archives to download and extract
      structure:
        - archive_name:
            type: string
            description: Archive name identifier.
      pattern: "*.zip"

  - test_data_prefix:
      type: string
      description: |
        Prefix for the output test data directory
      structure:
        - directory_prefix:
            type: string
            description: Directory prefix for test data.
      pattern: "*"

output:
  - test_data_directory:
      type: file
      description: |
        Directory containing test data extracted from the archive
      structure:
        - test_data_path:
            type: file
            description: Path to extracted test data directory.
      pattern: "*/{prefix}_*/archive_name"

  - versions:
      type: file
      description: |
        File containing software versions
      structure:
        - versions:
            type: file
            description: Versions YAML file.
      pattern: "versions.yml"

authors:
  - "@AlexVCaron"
