name: "output_template_space"
description: |
  This subworkflow is used to output files in a specific template space.
  It leverages the `templateflow` template repository to fetch the requested
  template and its associated files, then register the input files to the
  requested template space.

  The subworkflow relies on three parameters to be set:

    - params.template: the template to use (e.g., 'MNI152NLin2009cAsym')
    - params.templateflow_home: the path to the templateflow home directory.
      will be used to store the templateflow templates or to fetch them if
      they were already downloaded.
    - params.templateflow_res: the resolution of the template (e.g., 1)
    - params.templateflow_cohort: the cohort of the template (e.g., 1)

  An example of how to set the module's ext.args can be find in the
  `test/nextflow.config` file. Additional configuration for local templates
  are also available in the `test/local.config` file.

  To select the registration technique used to register the input files, use the
  following parameters :
  - params.run_easyreg : Use Easyreg any-to-any registration model
  - params.run_synthmorph : Use Synthmorph ML registration model

  Refer to the `registration` subworkflow and the modules it uses for configuration options.
keywords:
  - template
  - TemplateFlow
  - registration
components:
  - registration/antsapplytransforms
  - registration/tractogram
  - image/applymask
  - betcrop/fslbetcrop
  - utils/templateflow
  - registration
  - getoptionswithdefaults
input:
  - ch_anat:
      type: file
      description: |
        Channel containing the anatomical image to use to compute the
        registration into template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - anat:
            type: file
            description: Anatomical image file.
      pattern: "*.{nii,nii.gz}"
      mandatory: true
  - ch_nifti_files:
      type: file
      description: |
        Channel containing the NIfTI files to register into the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - nifti_files:
            type: files
            description: List of NIfTI files to register.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_mask_files:
      type: file
      description: |
        Channel containing binary mask files to transform in the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - mask_files:
            type: files
            description: List of binary mask files.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_labels_files:
      type: file
      description: |
        Channel containing label files to transform in the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - label_files:
            type: files
            description: List of label files.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_trk_files:
      type: file
      description: |
        Channel containing the TRK files to register into the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - trk_files:
            type: files
            description: List of tractogram files.
      pattern: "*.trk"
      mandatory: false
  - ch_freesurfer_license:
      type: file
      description: |
        ONLY USED WITH SYNTHMORPH REGISTRATION. The input channel containing the Freesurfer license file.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - license:
            type: file
            description: Freesurfer license file.
      pattern: "*.txt"
      mandatory: false
  - options:
      type: map
      description: Map of options for the output_template_space subworkflow.
      mandatory: false
      entries:
        template:
          type: string
          description: Name of the template to use (see https://templateflow.org).
          default: null
        templateflow_home:
          type: string
          description: Path to the templateflow local home directory where files are located and/or downloaded.
          default: "./templateflow"
        templateflow_res:
          type: integer
          description: Template resolution to use or download.
          default: null
        templateflow_cohort:
          type: string
          description: Name/type of the cohort to use.
          default: null
        run_easyreg:
          type: boolean
          description: Use Easyreg any-to-any registration model.
          default: false
        run_synthmorph:
          type: boolean
          description: Use Synthmorph ML registration model.
          default: false
output:
  - ch_t1w_tpl:
      type: file
      description: |
        Channel containing the T1w template.
      structure:
        - t1w:
            type: file
            description: T1w template image file.
      pattern: "*.{nii,nii.gz}"
  - ch_t2w_tpl:
      type: file
      description: |
        Channel containing the T2w template.
      structure:
        - t2w:
            type: file
            description: T2w template image file.
      pattern: "*.{nii,nii.gz}"
  - ch_registered_anat:
      type: file
      description: |
        Channel containing the anatomical image registered into the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - anat:
            type: file
            description: Registered anatomical image file.
      pattern: "*.{nii,nii.gz}"
  - ch_registered_nifti_files:
      type: file
      description: |
        Channel containing the NIfTI files registered into the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - nifti_files:
            type: files
            description: List of registered NIfTI files.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_registered_mask_files:
      type: file
      description: |
        Channel containing the mask files registered into the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - mask_files:
            type: files
            description: List of registered mask files.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_registered_labels_files:
      type: file
      description: |
        Channel containing the label files registered into the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - label_files:
            type: files
            description: List of registered label files.
      pattern: "*.{nii,nii.gz}"
      mandatory: false
  - ch_registered_trk_files:
      type: file
      description: |
        Channel containing the TRK files registered into the template space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - trk_files:
            type: files
            description: List of registered tractogram files.
      pattern: "*.trk"
      mandatory: false
  - mqc:
      type: file
      description: |
        Channel containing the MultiQC report of the registration.
      structure:
        - mqc:
            type: file
            description: MultiQC report file.
      pattern: "*mqc.*"
      mandatory: false
  - versions:
      type: file
      description: |
        File containing software versions
      structure:
        - versions:
            type: file
            description: Versions YAML file.
      pattern: "versions.yml"
authors:
  - "@gagnonanthony"
  - "@AlexVCaron"
maintainers:
  - "@gagnonanthony"
