# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: registration_convert
description: Freesurfer transform conversion tool. Default usage is aim at receiving
  freesurfer format and converting to ANTs (ITK). See lta_convert --help and mri_warp_convert
  --help for options.
keywords:
  - Registration
  - Brain imaging
  - MRI
  - Conversion
tools:
  - Freesurfer:
      description: |
        Open source neuroimaging toolkit for processing, analyzing, and visualizing human brain MR images.
      homepage: https://surfer.nmr.mgh.harvard.edu/
      doi: 10.1016/j.neuroimage.2012.01.021
      identifier: ""
args:
  - invert:
      type: boolean
      description: FOR AFFINE CONVERSION ONLY. Invert the transformation.
      default: false
  - conform:
      type: boolean
      description: FOR AFFINE CONVERSION ONLY. Conform target geometry before conversion (see freesurfer documentation).
      default: false
  - output_space:
      type: string
      description: FOR AFFINE CONVERSION ONLY. Reference space to convert to. Default is ras2ras.
      default: "ras2ras"
      choices:
        - ras2ras
        - vox2vox
        - register_dat
  - downsample:
      type: boolean
      description: FOR WARP CONVERSION ONLY. Downsample the input warp to 2mm isotropic resolution.
      default: false
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - transformation:
        type: file
        description: Input transformation to convert.
        pattern: "*.{nii,nii.gz,mgz,m3z,lta,txt,xfm,dat}"
        mandatory: true
        ontologies: []
    - input_type:
        type: string
        description: |
          Type of input transformation :
            - affine : lta, fsl, mni, reg, niftyreg, itk, vox
            - deform : m3z, fsl, lps, itk, ras, vox
        mandatory: true
        choices:
          - lta
          - fsl
          - mni
          - reg
          - niftyreg
          - itk
          - vox
          - m3z
          - fsl
          - lps
          - ras
          - vox
    - output_type:
        type: string
        description: |
          Type of output transformation :
            - affine : lta, fsl, mni, reg, niftyreg, itk
            - deform : m3z, fsl, lps, itk, ras, vox
        mandatory: true
        choices:
          - lta
          - fsl
          - mni
          - reg
          - niftyreg
          - itk
          - vox
          - m3z
          - fsl
          - lps
          - ras
          - vox
    - reference:
        type: file
        description: |
          Reference volume used for registration. For affine transformations, it's usually the target
          image, and for warp the moving (source) image. Validate with the tools you used to generate
          the transformation.
        pattern: "*.{nii,nii.gz}"
        mandatory: true
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - affine_source:
        type: file
        description: ONLY USED FOR CONVERSION OF AFFINES IN LTA FORMAT. Moving (source) Nifti volume used for registration.
        pattern: "*.{nii,nii.gz}"
        mandatory: false
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - fs_license:
        type: file
        description:
          The path to your FreeSurfer license. To get one, go to https://surfer.nmr.mgh.harvard.edu/registration.html.
          Optional. If you have already set your license as prescribed by Freesurfer
          (copied to a .license file in your $FREESURFER_HOME), this is not required.
        pattern: "*.txt"
        mandatory: true
        ontologies: []
output:
  transformation:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*out_{affine,warp}.{nii,nii.gz,mgz,m3z,txt,lta,mat,dat}":
          type: file
          description: Affine or warp converted to the desired format.
          pattern: "*out_{affine,warp}.{nii,nii.gz,mgz,m3z,txt,lta,mat,dat}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@anroy1"
  - "@AlexVCaron"
