name: Run checks Suite
on:
  workflow_call:
    inputs:
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "25.04.6"
      nf_core_version:
        description: "nf-core version to use"
        required: false
        type: string
        default: "2.14.*"
      nf_test_version:
        description: "nf-test version to use"
        required: false
        type: string
        default: "0.9.0"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"
          cache: "pip"

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        # FIXME Flip this off once we get to less than a couple hundred. Adding
        # this so it will only run against changed files. It'll make it much
        # easier to fix these as they come up rather than everything at once.
        with:
          extra_args: ""

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Prettier
        run: npm ci

      - name: Run Prettier --check
        run: npx prettier --check .

  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: "npm"

      - name: Install editorconfig-checker
        run: npm ci

      - name: Run ECLint check
        run: npx editorconfig-checker -exclude README.md $(git ls-files | grep -v test)

  lint-changes:
    name: lint - changes
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha || github.event.before }}
    outputs:
      paths: ${{ steps.changes.outputs.components }}
      modules: ${{ steps.components.outputs.modules }}
      subworkflows: ${{ steps.components.outputs.subworkflows }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: List nf-test files
        id: changes
        uses: adamrtalbot/detect-nf-test-changes@de3c3c8e113031b4f15a3c1104b5f135e8346997 # v0.0.6
        with:
          head: ${{ github.sha }}
          base: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha || github.event.before }}
          n_parents: 2

      - name: Separate modules and subworkflows
        id: components
        run: |
          echo modules=$(echo '${{ steps.changes.outputs.components }}' | jq -c '. | map(select(contains("modules"))) | map(gsub("modules/nf-neuro/"; ""))') >> $GITHUB_OUTPUT
          echo subworkflows=$(echo '${{ steps.changes.outputs.components }}' | jq '. | map(select(contains("subworkflows"))) | map(gsub("subworkflows/nf-neuro/"; ""))') >> $GITHUB_OUTPUT

      - name: debug
        run: |
          echo ${{ steps.components.outputs.modules }}
          echo ${{ steps.components.outputs.subworkflows }}

  nf-test-changes:
    name: test - changes
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha || github.event.before }}
    outputs:
      paths: ${{ steps.changes.outputs.components }}
      modules: ${{ steps.components.outputs.modules }}
      subworkflows: ${{ steps.components.outputs.subworkflows }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: List nf-test files
        id: changes
        uses: adamrtalbot/detect-nf-test-changes@de3c3c8e113031b4f15a3c1104b5f135e8346997 # v0.0.6
        with:
          head: ${{ github.sha }}
          base: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha || github.event.before }}
          n_parents: 2
          ignored: "*meta.yml"

      - name: Separate modules and subworkflows
        id: components
        run: |
          echo modules=$(echo '${{ steps.changes.outputs.components }}' | jq -c '. | map(select(contains("modules"))) | map(gsub("modules/nf-neuro/"; ""))') >> $GITHUB_OUTPUT
          echo subworkflows=$(echo '${{ steps.changes.outputs.components }}' | jq '. | map(select(contains("subworkflows"))) | map(gsub("subworkflows/nf-neuro/"; ""))') >> $GITHUB_OUTPUT

      - name: debug
        run: |
          echo ${{ steps.components.outputs.modules }}
          echo ${{ steps.components.outputs.subworkflows }}

  lint-modules:
    name: lint - modules
    needs: [lint-changes]
    if: ${{ (needs.lint-changes.outputs.modules != '[]') }}
    strategy:
      fail-fast: false
      matrix:
        module: ["${{ fromJson(needs.lint-changes.outputs.modules) }}"]
    uses: ./.github/workflows/lint_component.yml
    with:
      type: "module"
      component: ${{ matrix.module }}
      nextflow_version: ${{ inputs.nextflow_version }}
    secrets: inherit

  lint-subworkflows:
    name: lint - subworkflows
    needs: [lint-changes]
    if: ${{ ( needs.lint-changes.outputs.subworkflows != '[]') }}
    strategy:
      fail-fast: false
      matrix:
        subworkflow: ["${{ fromJson(needs.lint-changes.outputs.subworkflows) }}"]
    uses: ./.github/workflows/lint_component.yml
    with:
      type: "subworkflow"
      component: ${{ matrix.subworkflow }}
      nextflow_version: ${{ inputs.nextflow_version }}
    secrets: inherit

  nf-test:
    name: test
    needs: [nf-test-changes]
    if: ${{ ( github.repository == 'scilus/nf-neuro' ) && ( needs.nf-test-changes.outputs.paths != '[]' ) }}
    strategy:
      fail-fast: false
      matrix:
        path: ["${{ fromJson(needs.nf-test-changes.outputs.paths) }}"]
        include:
          - profile: docker
          - runner: scilus-docker
          - runner: scilus-docker-large
            path: modules/nf-neuro/registration/easyreg
          - runner: scilus-docker-large
            path: modules/nf-neuro/segmentation/synthseg
          - runner: scilus-docker-large
            path: modules/nf-neuro/betcrop/synthbet
          - runner: scilus-docker-large
            path: modules/nf-neuro/registration/synthmorph
        exclude:
          - path: subworkflows/nf-neuro/load_test_data
    uses: ./.github/workflows/test_component.yml
    with:
      profile: ${{ matrix.profile }}
      paths: ${{ matrix.path }}
      runner: ${{ matrix.runner }}
      nextflow_version: ${{ inputs.nextflow_version }}
      nf_test_version: ${{ inputs.nf_test_version }}
    secrets: inherit

  upload-reports:
    name: report
    needs: [nf-test-changes, nf-test]
    if: ${{ ( needs.nf-test-changes.outputs.paths != '[]' ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/upload-artifact/merge@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        continue-on-error: true
        with:
          name: nf-test-reports
          pattern: reports-*
          delete-merged: true
          retention-days: 10
          compression-level: 9

  confirm-pass:
    name: status
    runs-on: ubuntu-latest
    needs:
      [prettier, editorconfig, nf-test-changes, lint-changes, lint-modules, lint-subworkflows, nf-test, upload-reports]
    if: ${{ !cancelled() }}
    steps:
      - name: All tests ok
        if: ${{ success() || !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: One or more tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: debug-print
        if: ${{ !cancelled() }}
        run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
